config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :articles
  end
  namespace :admin do
    resources :categories
  end
  namespace :admin do
    resources :kinds
  end
  namespace :admin do
    resources :thematics
  end
  devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin/article.rb
class Admin::Article < ApplicationRecord
  belongs_to :admin_category, :class_name => 'Admin::Category'
end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < ApplicationController
  before_action :set_admin_article, only: [:show, :edit, :update, :destroy]

  # GET /admin/articles
  # GET /admin/articles.json
  def index
    @admin_articles = Admin::Article.all
  end

  # GET /admin/articles/1
  # GET /admin/articles/1.json
  def show
  end

  # GET /admin/articles/new
  def new
    @admin_article = Admin::Article.new
  end

  # GET /admin/articles/1/edit
  def edit
  end

  # POST /admin/articles
  # POST /admin/articles.json
  def create
    @admin_article = Admin::Article.new(admin_article_params)

    respond_to do |format|
      if @admin_article.save
        format.html { redirect_to @admin_article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @admin_article }
      else
        format.html { render :new }
        format.json { render json: @admin_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/articles/1
  # PATCH/PUT /admin/articles/1.json
  def update
    respond_to do |format|
      if @admin_article.update(admin_article_params)
        format.html { redirect_to @admin_article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_article }
      else
        format.html { render :edit }
        format.json { render json: @admin_article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/articles/1
  # DELETE /admin/articles/1.json
  def destroy
    @admin_article.destroy
    respond_to do |format|
      format.html { redirect_to admin_articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_article
      @admin_article = Admin::Article.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_article_params
      params.require(:admin_article).permit(:name, :description, :price, :feature, :admin_category_id)
    end
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/views/admin/articles/_form.html.erb
<%= form_with(model: admin_article, local: true) do |form| %>
  <% if admin_article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_article.errors.count, "error") %> prohibited this admin_article from being saved:</h2>

      <ul>
        <% admin_article.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :description %>
    <%= form.text_field :description %>
  </div>

  <div class="field">
    <%= form.label :price %>
    <%= form.text_field :price %>
  </div>

  <div class="field">
    <%= form.label :feature %>
    <%= form.text_field :feature %>
  </div>

  <div class="field">
    <%= form.label :admin_category_id %>
    <%= form.text_field :admin_category_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/articles/edit.html.erb
<h1>Editing Admin Article</h1>

<%= render 'form', admin_article: @admin_article %>

<%= link_to 'Show', @admin_article %> |
<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Articles</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Price</th>
      <th>Feature</th>
      <th>Admin category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_articles.each do |admin_article| %>
      <tr>
        <td><%= admin_article.name %></td>
        <td><%= admin_article.description %></td>
        <td><%= admin_article.price %></td>
        <td><%= admin_article.feature %></td>
        <td><%= admin_article.admin_category_id %></td>
        <td><%= link_to 'Show', admin_article %></td>
        <td><%= link_to 'Edit', edit_admin_article_path(admin_article) %></td>
        <td><%= link_to 'Destroy', admin_article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Article', new_admin_article_path %>

app/views/admin/articles/new.html.erb
<h1>New Admin Article</h1>

<%= render 'form', admin_article: @admin_article %>

<%= link_to 'Back', admin_articles_path %>

app/views/admin/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_article.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @admin_article.description %>
</p>

<p>
  <strong>Price:</strong>
  <%= @admin_article.price %>
</p>

<p>
  <strong>Feature:</strong>
  <%= @admin_article.feature %>
</p>

<p>
  <strong>Admin category:</strong>
  <%= @admin_article.admin_category_id %>
</p>

<%= link_to 'Edit', edit_admin_article_path(@admin_article) %> |
<%= link_to 'Back', admin_articles_path %>