config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :articles
  end
  namespace :admin do
    resources :categories
  end
  namespace :admin do
    resources :kinds
  end
  namespace :admin do
    resources :thematics
  end
  devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin/kind.rb
class Admin::Kind < ApplicationRecord
  belongs_to :admin_thematic, :class_name => 'Admin::Thematic'
end

app/controllers/admin/kinds_controller.rb
class Admin::KindsController < ApplicationController
  before_action :set_admin_kind, only: [:show, :edit, :update, :destroy]

  # GET /admin/kinds
  # GET /admin/kinds.json
  def index
    @admin_kinds = Admin::Kind.all
  end

  # GET /admin/kinds/1
  # GET /admin/kinds/1.json
  def show
  end

  # GET /admin/kinds/new
  def new
    @admin_kind = Admin::Kind.new
  end

  # GET /admin/kinds/1/edit
  def edit
  end

  # POST /admin/kinds
  # POST /admin/kinds.json
  def create
    @admin_kind = Admin::Kind.new(admin_kind_params)

    respond_to do |format|
      if @admin_kind.save
        format.html { redirect_to @admin_kind, notice: 'Kind was successfully created.' }
        format.json { render :show, status: :created, location: @admin_kind }
      else
        format.html { render :new }
        format.json { render json: @admin_kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/kinds/1
  # PATCH/PUT /admin/kinds/1.json
  def update
    respond_to do |format|
      if @admin_kind.update(admin_kind_params)
        format.html { redirect_to @admin_kind, notice: 'Kind was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_kind }
      else
        format.html { render :edit }
        format.json { render json: @admin_kind.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/kinds/1
  # DELETE /admin/kinds/1.json
  def destroy
    @admin_kind.destroy
    respond_to do |format|
      format.html { redirect_to admin_kinds_url, notice: 'Kind was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_kind
      @admin_kind = Admin::Kind.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_kind_params
      params.require(:admin_kind).permit(:name, :admin_thematic_id)
    end
end

app/helpers/admin/kinds_helper.rb
module Admin::KindsHelper
end

app/views/admin/kinds/_form.html.erb
<%= form_with(model: admin_kind, local: true) do |form| %>
  <% if admin_kind.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_kind.errors.count, "error") %> prohibited this admin_kind from being saved:</h2>

      <ul>
        <% admin_kind.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :admin_thematic_id %>
    <%= form.text_field :admin_thematic_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/kinds/edit.html.erb
<h1>Editing Admin Kind</h1>

<%= render 'form', admin_kind: @admin_kind %>

<%= link_to 'Show', @admin_kind %> |
<%= link_to 'Back', admin_kinds_path %>

app/views/admin/kinds/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Kinds</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Admin thematic</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_kinds.each do |admin_kind| %>
      <tr>
        <td><%= admin_kind.name %></td>
        <td><%= admin_kind.admin_thematic_id %></td>
        <td><%= link_to 'Show', admin_kind %></td>
        <td><%= link_to 'Edit', edit_admin_kind_path(admin_kind) %></td>
        <td><%= link_to 'Destroy', admin_kind, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Kind', new_admin_kind_path %>

app/views/admin/kinds/new.html.erb
<h1>New Admin Kind</h1>

<%= render 'form', admin_kind: @admin_kind %>

<%= link_to 'Back', admin_kinds_path %>

app/views/admin/kinds/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_kind.name %>
</p>

<p>
  <strong>Admin thematic:</strong>
  <%= @admin_kind.admin_thematic_id %>
</p>

<%= link_to 'Edit', edit_admin_kind_path(@admin_kind) %> |
<%= link_to 'Back', admin_kinds_path %>