config/routes.rb
Rails.application.routes.draw do
  namespace :admin do
    resources :articles
  end
  namespace :admin do
    resources :categories
  end
  namespace :admin do
    resources :kinds
  end
  namespace :admin do
    resources :thematics
  end
  devise_for :admins
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin/thematic.rb
class Admin::Thematic < ApplicationRecord
end

app/controllers/admin/thematics_controller.rb
class Admin::ThematicsController < ApplicationController
  before_action :set_admin_thematic, only: [:show, :edit, :update, :destroy]

  # GET /admin/thematics
  # GET /admin/thematics.json
  def index
    @admin_thematics = Admin::Thematic.all
  end

  # GET /admin/thematics/1
  # GET /admin/thematics/1.json
  def show
  end

  # GET /admin/thematics/new
  def new
    @admin_thematic = Admin::Thematic.new
  end

  # GET /admin/thematics/1/edit
  def edit
  end

  # POST /admin/thematics
  # POST /admin/thematics.json
  def create
    @admin_thematic = Admin::Thematic.new(admin_thematic_params)

    respond_to do |format|
      if @admin_thematic.save
        format.html { redirect_to @admin_thematic, notice: 'Thematic was successfully created.' }
        format.json { render :show, status: :created, location: @admin_thematic }
      else
        format.html { render :new }
        format.json { render json: @admin_thematic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /admin/thematics/1
  # PATCH/PUT /admin/thematics/1.json
  def update
    respond_to do |format|
      if @admin_thematic.update(admin_thematic_params)
        format.html { redirect_to @admin_thematic, notice: 'Thematic was successfully updated.' }
        format.json { render :show, status: :ok, location: @admin_thematic }
      else
        format.html { render :edit }
        format.json { render json: @admin_thematic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /admin/thematics/1
  # DELETE /admin/thematics/1.json
  def destroy
    @admin_thematic.destroy
    respond_to do |format|
      format.html { redirect_to admin_thematics_url, notice: 'Thematic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_admin_thematic
      @admin_thematic = Admin::Thematic.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def admin_thematic_params
      params.require(:admin_thematic).permit(:name)
    end
end

app/helpers/admin/thematics_helper.rb
module Admin::ThematicsHelper
end

app/views/admin/thematics/_form.html.erb
<%= form_with(model: admin_thematic, local: true) do |form| %>
  <% if admin_thematic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(admin_thematic.errors.count, "error") %> prohibited this admin_thematic from being saved:</h2>

      <ul>
        <% admin_thematic.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/thematics/edit.html.erb
<h1>Editing Admin Thematic</h1>

<%= render 'form', admin_thematic: @admin_thematic %>

<%= link_to 'Show', @admin_thematic %> |
<%= link_to 'Back', admin_thematics_path %>

app/views/admin/thematics/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Admin Thematics</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @admin_thematics.each do |admin_thematic| %>
      <tr>
        <td><%= admin_thematic.name %></td>
        <td><%= link_to 'Edit', edit_admin_thematic_path(admin_thematic) %></td>
        <td><%= link_to 'Destroy', admin_thematic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Admin Thematic', new_admin_thematic_path %>

app/views/admin/thematics/new.html.erb
<h1>New Admin Thematic</h1>

<%= render 'form', admin_thematic: @admin_thematic %>

<%= link_to 'Back', admin_thematics_path %>

app/views/admin/thematics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @admin_thematic.name %>
</p>

<%= link_to 'Edit', edit_admin_thematic_path(@admin_thematic) %> |
<%= link_to 'Back', admin_thematics_path %>